export const allTextureKeys = {
  shipBlue: "shipBlue",
  shipBlue2: "shipBlue2",
  bomb: "bomb",
  musicOn: "musicOn",
  musicOff: "musicOff",
  effectsOn: "effectsOn",
  effectsOff: "effectsOff",
  enemyShip: "enemyShip",
  man: "man",
  man2: "man2",
  woman: "woman",
  TombStone1: "TombStone1",
  TombStone2: "TombStone2",
  spaceShip: "spaceShip",
  bullet1: "bullet1",
  bullet2: "bullet2",
  explosion: "explosion",
  explosion1: "explosion1",
  explosion2: "explosion2",
  explosion3: "explosion3",
};

const appTextures = {
    [allTextureKeys.shipBlue]: 'assets/sprites/enemy/shipBlue.png',
    [allTextureKeys.shipBlue2]: 'assets/sprites/enemy/shipBlue2.png',
    [allTextureKeys.bomb]: 'assets/sprites/bomb.png',
    [allTextureKeys.musicOn]: 'assets/sprites/ui/music_on.png',
    [allTextureKeys.musicOff]: 'assets/sprites/ui/music_off.png',
    [allTextureKeys.effectsOn]: 'assets/sprites/ui/volume_on.png',
    [allTextureKeys.effectsOff]: 'assets/sprites/ui/volume_off.png',
    [allTextureKeys.enemyShip]: 'assets/sprites/enemy/shipBlue.png',
    [allTextureKeys.man]: 'assets/sprites/people/man.png',
    [allTextureKeys.man2]: 'assets/sprites/people/man2.png',
    [allTextureKeys.woman]: 'assets/sprites/people/woman.png',
    [allTextureKeys.TombStone1]: 'assets/sprites/people/TombStone1.png',
    [allTextureKeys.TombStone2]: 'assets/sprites/people/TombStone2.png',
    [allTextureKeys.spaceShip]: 'assets/sprites/player.png',
    [allTextureKeys.bullet1]: 'assets/sprites/bullets/bullet1.json',
    [allTextureKeys.bullet2]: 'assets/sprites/bullets/bullet2.json',
    [allTextureKeys.explosion]: 'assets/sprites/explosion/explosion.json',
    [allTextureKeys.explosion1]: 'assets/sprites/explosion/explosion1.json',
    [allTextureKeys.explosion2]: 'assets/sprites/explosion/explosion2.json',
    [allTextureKeys.explosion3]: 'assets/sprites/explosion/explosion3.json',
} 

export default appTextures