export const allTextureKeys = {
  shipBlue: "shipBlue",
  shipBlue2: "shipBlue2",
  bomb: "bomb",
  musicOn: "musicOn",
  musicOff: "musicOff",
  effectsOn: "effectsOn",
  effectsOff: "effectsOff",
  enemyShip: "enemyShip",
  man: "man",
  man2: "man2",
  woman: "woman",
  TombStone1: "TombStone1",
  TombStone2: "TombStone2",
  spaceShip: "spaceShip",
  bullet1: "bullet1",
  bullet2: "bullet2",
  explosion: "explosion",
  explosion1: "explosion1",
  explosion2: "explosion2",
  explosion3: "explosion3",
  background1: "background1",
  background2: "background2",
  background3: "background3",
  background4: "background4",
  background5: "background5",
  background6: "background6",
  background7: "background7",
  background8: "background8",
  background9: "background9",
  background10: "background10",
 
};

const appTextures = {
    [allTextureKeys.shipBlue]: 'assets/sprites/enemy/shipBlue.png',
    [allTextureKeys.shipBlue2]: 'assets/sprites/enemy/shipBlue2.png',
    [allTextureKeys.bomb]: 'assets/sprites/bomb.png',
    [allTextureKeys.musicOn]: 'assets/sprites/ui/music_on.png',
    [allTextureKeys.musicOff]: 'assets/sprites/ui/music_off.png',
    [allTextureKeys.effectsOn]: 'assets/sprites/ui/volume_on.png',
    [allTextureKeys.effectsOff]: 'assets/sprites/ui/volume_off.png',
    [allTextureKeys.enemyShip]: 'assets/sprites/enemy/shipBlue.png',
    [allTextureKeys.man]: 'assets/sprites/people/man.png',
    [allTextureKeys.man2]: 'assets/sprites/people/man2.png',
    [allTextureKeys.woman]: 'assets/sprites/people/woman.png',
    [allTextureKeys.TombStone1]: 'assets/sprites/people/TombStone1.png',
    [allTextureKeys.TombStone2]: 'assets/sprites/people/TombStone2.png',
    [allTextureKeys.spaceShip]: 'assets/sprites/player.png',
    [allTextureKeys.bullet1]: 'assets/sprites/bullets/bullet1.json',
    [allTextureKeys.bullet2]: 'assets/sprites/bullets/bullet2.json',
    [allTextureKeys.explosion]: 'assets/sprites/explosion/explosion.json',
    [allTextureKeys.explosion1]: 'assets/sprites/explosion/explosion1.json',
    [allTextureKeys.explosion2]: 'assets/sprites/explosion/explosion2.json',
    [allTextureKeys.explosion3]: 'assets/sprites/explosion/explosion3.json',
    [allTextureKeys.background1]: 'assets/backgrounds/background1.png',
    [allTextureKeys.background2]: 'assets/backgrounds/background2.png',
    [allTextureKeys.background3]: 'assets/backgrounds/background3.png',
    [allTextureKeys.background4]: 'assets/backgrounds/background4.png',
    [allTextureKeys.background5]: 'assets/backgrounds/background5.png',
    [allTextureKeys.background6]: 'assets/backgrounds/background6.png',
    [allTextureKeys.background7]: 'assets/backgrounds/background7.png',
    [allTextureKeys.background8]: 'assets/backgrounds/background8.png',
    [allTextureKeys.background9]: 'assets/backgrounds/background9.png',
    [allTextureKeys.background10]: 'assets/backgrounds/background10.png',
} 

export default appTextures